export const ROUTE = Object.freeze({
  INDEX: `/`,
  PAGE_BUTTON: `/nexsoft/button`,
  PAGE_BUTTON_ICON: `/nexsoft/button_icon`,
  PAGE_BUTTON_GROUP: `/nexsoft/buttongroup`,
  PAGE_PASSWORD: `/nexsoft/textfieldpassword`,
  PAGE_DATEPICKER: `/nexsoft/datepicker`,
  PAGE_CHECKBOX: `/nexsoft/checkbox`,
  PAGE_CHECKBOX_GROUP: `/nexsoft/checkbox_group`,
  PAGE_INPUT_PHONE_NUMBER :`/nexsoft/phone_number`,
  PAGE_INPUT :`/nexsoft/input`,
  PAGE_SELECT :`/nexsoft/select`,
  PAGE_SEARCH : `/nexsoft/search`,
  PAGE_PIN : `/nexsoft/pin`,
  PAGE_INPUT_BUTTON : `/nexsoft/inputbutton`,
  PAGE_RADIO : `nexsoft/radio`,
  PAGE_RADIO_GROUP : `nexsoft/radio_group`,
  PAGE_UPLOAD_FILE : `nexsoft/upload_file`,
  PAGE_BREADCRUMB : `nexsoft/breadcrumb`,
  PAGE_DIALOG : `/nexsoft/dialog`,
  PAGE_DIVIDER : `nexsoft/divider`,
  PAGE_RATING: 'nexsoft/rating',
  PAGE_BUTTON_LOGIN_GROCHAT : `nexsoft/button_login_grochat`,
  PAGE_ALERT : `/nexsoft/alert`,
  PAGE_LEGEND: `nexsoft/legend`,
  PAGE_FIELD_INPUT: `nexsoft/field_input`,
  PAGE_TEXT_AREA : `nexsoft/text_area`,
  PAGE_LIST:`nexsoft/list`,
  PAGE_TOGGLE : `nexsoft/toggle`,
  PAGE_TOGGLE_GROUP : `nexsoft/toggle_group`,
  PAGE_INFO_CARD : `nexsoft/info_card`,
  PAGE_TOOLTIPS : `nexsoft/tooltips`,
  PAGE_AVATAR : `/nexsoft/avatar`,
  PAGE_AVATAR_GROUP : `/nexsoft/avatar_group`,
  PAGE_TAG : `nexsoft/tag`,
  PAGE_PREPOST_TAB: `nexsoft/pre_post_tab`,
  PAGE_TABLE: `nexsoft/table`,
  PAGE_STEPS : `nexsoft/steps`,
  PAGE_BADGE: `nexsoft/badge`,
  PAGE_SLIDER: `nexsoft/slider`,
  PAGE_TABS : `nexsoft/tabs`,
  PAGE_PROGRESS_BAR : `nexsoft/progress_bar`,
  PAGE_HTML_AREA: `nexsoft/html_area`,
  PAGE_MULTIPLE_SELECT: `nexsoft/multiple_select`,
  PAGE_IMAGE : `nexsoft/image`,
  PAGE_VIDEO: `nexsoft/video`,
  PAGE_PROGRESS_TRACK : `nexsoft/progress_track`,
  PAGE_TRANSFER_FILE :  `nexsoft/transfer_file`,
  PAGE_TRANSFER_LIST :  `nexsoft/transfer_list`,
  PAGE_CARD:`/nexsoft/card`,
  PAGE_TIMEPICKER: `nexsoft/timepicker`,
  PAGE_PREVIEW_ADS:`/nexsoft/preview_ads`,
  PAGE_REGION_SELECTS: `nexsoft/region_selects`
})
