export const classNameDefault = {
  selectBox: `select-box`,
  activePage: `active-page`,
  table: `table`,
  tableHeader: `table-header`,
  containerFixXCol: `container-fix-col`,
  shadowTable: `shadow-table`,
  tableList: `table-list`,
  itemLink: `item-link`,
  tableFooter: `table-footer`,
  labelFooter: `label-footer`,
  pagination: `pagination`,
  iconActive: `icon-active`,
  iconDeactive: `icon-deactive`,
  iconBreadcrumb: `iconBreadcrumb`,
  th: `th`,
  disablePagination: `disablePagination`,
  valueToggleActive: `value-toggle-active`,
  valueToggle: `value-toggle`,
  switch: `switch`,
  slider: `slider`,
};
