export const idDefault = {
  TextboxSingleLine: "tsl",
  AutoCompleteTextboxSingleLine: "actsl",
  AutoCompleteOption: "acopt",
  TextboxMultipleLine: "tml",
  DropdownList: "ddl",
  DropdownSearch: "dds",
  CheckBox: "ckb",
  RadioButton: "rdbn",
  Label: "lbl",
  DatePickList: "dpl",
  Search: "sch",
  Photo: "pht",
  ToggleSwitch: "tgl",
  LookUpMultiLineOption: "lumlo",
  FileUploader: "fup",
  Map: "map ",
  SignaturePad: "sgp",
  ProgressBar: "pgb",
  MultiSelect: "mls",
  Icon: "ico",
  orderList: "ols",
  unOrderList: "uls",
  list: "lis",
  Field: "fld",
  Input: "ipt",
  hyperlink: "hyp",
  breadcrumb: "brc",
  input: "input",
  slider: "slider",
  value: "value",
  icon: "icon",
};
